apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcare-sa
  namespace: healthcare
  annotations:
    iam.gke.io/gcp-service-account: healthcare-workload-dev@massive-sandbox-477717-k3.iam.gserviceaccount.com
